### ISSUE TITLE
Exception sending phone home data on flaky wifi connection

### ISSUE THREAD

**Issue by mdoube** [bonej-org/bonej#20]
When using BoneJ 1.4.1 on a Windows machine with flaky wifi - dropping in and out 'limited connectivity', this pops up. Looks like it relates to a failed DNS lookup.

`java.net.UnknownHostException: www.google-analytics.com
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:195)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
at java.net.Socket.connect(Socket.java:529)
at java.net.Socket.connect(Socket.java:478)
at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:394)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
at sun.net.www.http.HttpClient.<init>(HttpClient.java:233)
at sun.net.www.http.HttpClient.New(HttpClient.java:306)
at sun.net.www.http.HttpClient.New(HttpClient.java:323)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:970)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:911)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:836)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1172)
at org.doube.util.UsageReporter.send(UsageReporter.java:220)
at org.doube.util.DeleteSliceRange.run(DeleteSliceRange.java:52)
at ij.IJ.runUserPlugIn(IJ.java:212)
at ij.IJ.runPlugIn(IJ.java:176)
at ij.Executer.runCommand(Executer.java:132)
at ij.Executer.run(Executer.java:65)
at java.lang.Thread.run(Thread.java:662)`

**Comment by mdoube** [comment]
UnknownHostException is handled already by catching IOException. Making the exception available only when in debug mode means that ordinary users are not annoyed by this information, while it is available for diagnostics if debug mode is activated.
