### ISSUE TITLE
TriplePointAngles nth edge pixel throws Exception

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#23]
_SkeletonAngles_ (BoneJ > Triple Point Angles) throws an _IndexOutOfBounds_ exception when run with the options _Use: nth edge pixel_ and _nth pixel: 0_

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.bonej.SkeletonAngles.getNthPoint(SkeletonAngles.java:189)
    at org.bonej.SkeletonAngles.vertexAngle(SkeletonAngles.java:178)
    at org.bonej.SkeletonAngles.calculateTriplePointAngles(SkeletonAngles.java:144)
    at org.bonej.SkeletonAngles.run(SkeletonAngles.java:71)
    at ij.IJ.runUserPlugIn(IJ.java:212)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:136)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by rimadoma** [comment]
@mdoube ~~Is _nth edge pixel_ with _nth pixel 0_ essentially the same thing than running the plugin with _opposite vertex_?~~

Nevermind, the same exception happens even if _nth pixel_ != 0

**Comment by rimadoma** [comment]
NB I can only reproduce the bug with the image binary_trabeculae_small.tif
