### ISSUE TITLE
Distribution analysis throws NullPointerException

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#27]
Distribution analysis throws a `NullPointerException` when run with a 16-bit (unsigned) greyscale image. 
### Steps to  reproduce

1) Open _blobs.gif_ (_File > Open Samples > Blobs_)
2) Convert to 16-bits (_Image > Type > 16-bit_)
3) Run _Plugins > pQCT > Distribution Analysis_
4) Press OK on the dialog

Throws an exception:

```
java.lang.NullPointerException
    at org.doube.bonej.pqct.Distribution_Analysis.run(Distribution_Analysis.java:327)
    at ij.IJ.runUserPlugIn(IJ.java:212)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:136)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Thread.java:745)
```

Originally reported at the ImageJ [forum](http://forum.imagej.net/t/density-distribution-error/1244)

**Comment by mdoube** [comment]
Fixed by https://github.com/mdoube/BoneJ/commit/c28c06400c8e4b885f599be7114717d7b4b242a2
