### ISSUE TITLE
AnisotropyTest.testCalculateSingleSphereIsotropy fails

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#36]
On rare occasion the method `AnisotropyTest.testCalculateSingleSphereIsotropy` throws an `AssertionError` because the tolerance for delta is too small. This time the test failed on the Jenkins server (in the BoneJ2 / Legacy module) causing the build to fail:

``` java
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.556 sec <<< FAILURE! - in org.bonej.plugins.AnisotropyTest
testCalculateSingleSphereIsotropy(org.bonej.plugins.AnisotropyTest)  Time elapsed: 0.583 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0.0> but was:<0.10016939634685473>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:494)
        at org.junit.Assert.assertEquals(Assert.java:592)
        at org.bonej.plugins.AnisotropyTest.testCalculateSingleSphereIsotropy(AnisotropyTest.java:57)
```

**Comment by rimadoma** [comment]
Commit https://github.com/bonej-org/bonej/pull/37/commits/9f688e4355836af93d4535a7642cf22a2e040336 fixes this issue by generating the noise map with a constant seed
